USE [master]
GO

/****** Object:  Database [DemoCRUD]    Script Date: 3/22/2021 1:47:23 PM ******/
CREATE DATABASE [DemoCRUD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DemoCRUD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DemoCRUD.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DemoCRUD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DemoCRUD_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DemoCRUD] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DemoCRUD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DemoCRUD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DemoCRUD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DemoCRUD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DemoCRUD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DemoCRUD] SET ARITHABORT OFF 
GO

ALTER DATABASE [DemoCRUD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DemoCRUD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DemoCRUD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DemoCRUD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DemoCRUD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DemoCRUD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DemoCRUD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DemoCRUD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DemoCRUD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DemoCRUD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DemoCRUD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DemoCRUD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DemoCRUD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DemoCRUD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DemoCRUD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DemoCRUD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DemoCRUD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DemoCRUD] SET RECOVERY FULL 
GO

ALTER DATABASE [DemoCRUD] SET  MULTI_USER 
GO

ALTER DATABASE [DemoCRUD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DemoCRUD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DemoCRUD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DemoCRUD] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DemoCRUD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DemoCRUD] SET  READ_WRITE 
GO

